#!/bin/bash

#Extract CofR

start=0.5
step=0.5
end=160
rm output*


for i in $(seq $start $step $end); do

	if [[ $i =~ \.0$ ]]; then
		folder_name=$(printf "%.0f" $i)
    	else
		folder_name=$(printf "%.1f" $i)
    	fi
		
	echo "Extract CofR from t = $folder_name"
	
	if [ -d "./$folder_name" ];then
		
		filename="$folder_name/uniform/sixDoFRigidBodyMotionState"
		
		line1=$(sed -n '19p' "$filename")
				
		numbers1=$(echo $line1 | awk -F'[()]' '{print $2}')
		
		echo "CofR = ( $numbers1 )"
		
		line2=$(sed -n '21p' "$filename")
		 
                #Pitch		
		numbers2=$(echo $line2 | awk  '{print $9}')
		X1=$numbers2
		Y1=$(python3 -c "import math; print(180 / math.pi * math.asin($X1))")
		echo "Pitch = ( $Y1 )"  #needs 180/pi*asin( )
                
                #Roll-X         
                numbers2=$(echo $line2 | awk  '{print $3}')
                X2=$numbers2
                numbers2=$(echo $line2 | awk  '{print $6}')
                X3=$numbers2
                Y3=$(python3 -c "import math; print(180 / math.pi * math.atan(- $X3 / $X2))")
                echo "Roll = ( $Y3 )"  #needs 180/pi*atan( - 6/3 )

                #Yaw-Z         
                numbers2=$(echo $line2 | awk  '{print $10}')
                X4=$numbers2
                numbers2=$(echo $line2 | awk  '{print $11}')
                X5=$numbers2
                Y2=$(python3 -c "import math; print(180 / math.pi * math.atan(- $X4 / $X5))")
                echo "Yaw = ( $Y2 )"  #needs 180/pi*asin( )

		echo "$folder_name $numbers1 $Y1 $Y2 $Y3" >> "output_CofR_plus.txt"
				
	fi			

done


gnuplot_script=$(cat << EOF

set terminal pngcairo size 1200,800
set output 'CofR_image_plus.png'
set multiplot layout 2,3 title " "

set title "Surge"
set xlabel "Time (s)"
set ylabel "Surge (m)"
plot "output_CofR_plus.txt" using 1:2 with points title ' '

set title "Sway"
set xlabel "Time (s)"
set ylabel "Sway (m)"
plot "output_CofR_plus.txt" using 1:3 with points title ' '

set title "Heave"
set xlabel "Time (s)"
set ylabel "Heave (m)"
plot "output_CofR_plus.txt" using 1:4 with points title ' '

set title "Pitch-Y"
set xlabel "Time (s)"
set ylabel "Pitch (degree)"
plot "output_CofR_plus.txt" using 1:5 with points title ' '

set title "Roll-X"
set xlabel "Time (s)"
set ylabel "Roll (degree)"
plot "output_CofR_plus.txt" using 1:6 with points title ' '

set title "Yaw-Z"
set xlabel "Time (s)"
set ylabel "Yaw (degree)"
plot "output_CofR_plus.txt" using 1:7 with points title ' '
EOF
)

echo "$gnuplot_script" | gnuplot

