#!/bin/bash

#Extract CofR

start=0.5
step=0.5
end=20
rm output*


for i in $(seq $start $step $end); do

	if [[ $i =~ \.0$ ]]; then
		folder_name=$(printf "%.0f" $i)
    	else
		folder_name=$(printf "%.1f" $i)
    	fi
		
	echo "Extract CofR from t = $folder_name"
	
	if [ -d "./$folder_name" ];then
		
		filename="$folder_name/uniform/sixDoFRigidBodyMotionState"
		
		line1=$(sed -n '19p' "$filename")
				
		numbers1=$(echo $line1 | awk -F'[()]' '{print $2}')
		
		echo "CofR = ( $numbers1 )"
		
		line2=$(sed -n '21p' "$filename")
				
		numbers2=$(echo $line2 | awk  '{print $9}')
		
		X=$numbers2
		#Y=$(echo "scale=10; 180/a(1) * a($X/sqrt(1-($X)*($X)))" | bc -l)
		Y=$(python3 -c "import math; print(180 / math.pi * math.asin($X))")
					
		echo "Pitch = ( $Y )"  #needs 180/pi*asin( )

		echo "$folder_name $numbers1 $Y" >> "output_CofR.txt"
				
	fi			

done


gnuplot_script=$(cat << EOF

set terminal pngcairo size 1200,800
set output 'CofR_image.png'
set multiplot layout 2,2 title " "

set title "Surge"
set xlabel "Time (s)"
set ylabel "Surge (m)"
plot "output_CofR.txt" using 1:2 with points title ' '

set title "Sway"
set xlabel "Time (s)"
set ylabel "Sway (m)"
plot "output_CofR.txt" using 1:3 with points title ' '

set title "Heave"
set xlabel "Time (s)"
set ylabel "Heave (m)"
plot "output_CofR.txt" using 1:4 with points title ' '

set title "Pitch"
set xlabel "Time (s)"
set ylabel "Pitch (degree)"
plot "output_CofR.txt" using 1:5 with points title ' '
EOF
)

echo "$gnuplot_script" | gnuplot

