#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

nProc=$(getNumberOfProcessors)

# Set solver name
#solver="mpirun --oversubscribe --mca btl ^tcp -np $nProc olaDyMFlow -parallel"
solver="mpirun -np $nProc overOlaDyMFlow -parallel"

# Run the solver
runApplication $solver
mv log.mpirun log.olaDymFlow
